[project]
name = "MSIAnalyzer"
version = "0.1.0"
description = "App to analyze MSI data"
authors = [
    {name = "Matteo Miotto", email = "miotsdata@gmail.com"},
]
dependencies = ["libviz>=0.1.0", "pyside6>=6.11.1"]
requires-python = "==3.13"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[tool.pdm]
distribution = true

[tool.pdm.dev-dependencies]
dev = [
    "-e file:///Users/matteomiotto/Desktop/metabolomics/libviz#egg=LibViz",
]
[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
