[project]
name = "MSIAnalyzer"
version = "0.1.0"
description = "App to analyze MSI data"
authors = [
    {name = "Matteo Miotto", email = "miotsdata@gmail.com"},
]
dependencies = ["libviz>=0.1.3", "plotly>=6.8.0", "anndata>=0.13.2", "tomli-w>=1.2.0", "matplotlib>=3.11.1", "kaleido>=1.3.0"]
requires-python = ">=3.13,<3.14"
readme = "README.md"
license = {text = "MIT"}

[project.optional-dependencies]
gui = ["pyside6>=6.11.1"]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project.scripts]
msianalyzer = "msianalyzer.cli.main:main"
msianalyzer-gui = "msianalyzer.gui.main:main"

[tool.pdm]
distribution = true

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "find-mfs>=0.4.0",
    "jupyter>=1.1.1",
    "pylint>=4.0.6",
    "pytest-mock>=3.15.1",
    "pytest-qt>=4.5.0",
    "hypothesis>=6.167.1",
    "mkdocstrings[python]>=1.0.6",
    "mkdocs-material>=9.7.7",
    "pyinstaller>=6.22.3",
]
